### ISSUE TITLE
Breakfast of champions

### ISSUE THREAD

**Issue by RommelTJ** [RomzaLabs/Food#1]
**I'm submitting a ...**

- [x] meal plan request
- [ ] grocery list request
- [ ] other

## Notes:

Let's start with breakfast, @leaningtower. Is there anything you wouldn't mind having for breakfast every day? I like coffee, so I'll add that, but you don't like yogurt. Can you suggest something? In the past I've had two large 🐔  🥚 .

**Comment by leaningtower** [comment]
I usually skip breakfast but if I'm hungry I'll eat an apple or some eggs. Maybe avocado toast if we have it.

**Comment by RommelTJ** [comment]
Awesome. I'll add eggs and fruit to the lists. 🥘
