### ISSUE TITLE
Dinner for Winners

### ISSUE THREAD

**Issue by RommelTJ** [RomzaLabs/Food#3]
**I'm submitting a ...**

- [x] meal plan request
- [x] grocery list request

## Notes:

So all that's left is setting up our dinners. I am open to suggestions. Didn't you mention something? I think I would like to eat more fish so that's what I'm thinking. I also think that I like pasta, so stuff like Ramen, Noodles, Spaghetti would be nice and easy.

**Comment by leaningtower** [comment]
I wanted to use up the tomato paste...

**Comment by RommelTJ** [comment]
@leaningtower How about Chicken Enchiladas?

**Comment by RommelTJ** [comment]
This is [a sample recipe](https://www.aberdeenskitchen.com/2016/03/red-chicken-enchiladas/) that just says "enchilada sauce", but the red sauces have a tomato base so we can use the paste to make a shit ton of it. And I know you ❤️ 🐔 & 🧀 .

**Comment by leaningtower** [comment]
Yessss that sounds good.

**Comment by RommelTJ** [comment]
Here's a Sauce recipe: https://www.yummly.com/recipe/Red-Enchilada-Sauce-Allrecipes 

Closing cuz I think we're set. I'll update the grocery list and meal plan soon.
